language: php
php:
  - '7.1'

services:
  - docker
 
install:
  - pip install awscli --user

before_script:
  - composer self-update
  - git clone --branch=8.x https://github.com/dru-io/Dru.io.git /opt/druio-html

script:
  - composer update --with-dependencies -d /opt/druio-html
  - tar czf druio.tar.gz -C /opt/druio-html
  - aws s3 rm s3://druio/druio.tar.gz
  - aws s3 cp druio.tar.gz s3://druio/druio.tar.gz
  - aws s3api put-object-acl --acl public-read --bucket druio --key druio.tar.gz

after_success:
  - echo 'ok'
