message: 'Сайт @site сейчас на техническом обслуживании. Скоро он заработает вновь. Благодарим вас за терпение.'
langcode: ru
_core:
  default_config_hash: Z5MXifrF77GEAgx0GQ6iWT8wStjFuY8BD9OruofWTJ8
